### ISSUE TITLE
'inspect' has no attribute 'getargspec'.

### ISSUE THREAD

**Issue by HammadRafique29** [kmike/pymorphy2#166] opened 2023-09-09 03:08 UTC
I am trying to run nltk django based project "findsimilar" and got this error.

![image](https://github.com/pymorphy2/pymorphy2/assets/112252001/8a80205b-850d-4ae2-875f-e3c997ade103)

**Comment by insolor** [comment] 2023-09-09 09:55
Duplicate of #159. Corresponding pull request: #161

In fact, this project is abandoned (related discussion: #160).

- You can use a workaround: https://github.com/pymorphy2/pymorphy2/issues/160#issuecomment-1486657176
- You can use a fork: https://github.com/no-plagiarism/pymorphy3
- There is another fork, but it haven't yet released on pypi.org: https://github.com/pymorphy2-fork

**Closed as completed** 2023-09-09 20:03 UTC

**Comment by doctorcolossus** [comment] 2024-06-10 21:35
https://github.com/pymorphy2/pymorphy2/pull/173

`patch /usr/lib/python3.12/site-packages/pymorphy2/units/base.py < patch`

```
--- /usr/lib/python3.12/site-packages/pymorphy2/units/base.py	2024-06-11 00:25:00.495794626 +0300
+++ /usr/lib/python3.11/site-packages/pymorphy2/units/base.py	2023-05-17 20:07:20.322965962 +0300
@@ -67,7 +67,7 @@
         """
         if cls.__init__ is object.__init__:
             return []
-        args, varargs, kw, default = inspect.getargspec(cls.__init__)
+        args, *_ = inspect.getfullargspec(cls.__init__)
         return sorted(args[1:])

     def _get_params(self):
```
